ALTER TABLE usuarios DROP COLUMN IF EXISTS ativo;

ALTER TABLE usuarios ADD COLUMN ativo BOOLEAN DEFAULT TRUE;

UPDATE usuarios SET ativo = TRUE WHERE ativo IS NULL;
ALTER TABLE usuarios ALTER COLUMN ativo SET NOT NULL;