@startuml Caneco_Cheio_Estados_Caixa
title Diagrama de Estados - Entidade Caixa (Vertical simplificado)

skinparam nodesep 90
skinparam ranksep 90
skinparam ArrowThickness 1.3
skinparam ArrowColor #444
skinparam state {
    BackgroundColor White
    BorderColor #222
    Padding 18
    RoundCorner 10
}

top to bottom direction

[*] --> ABERTO : abrirCaixa(saldoInicial)

ABERTO : entry / inicializarSaldo()
ABERTO : do / monitorarOperacoes()
ABERTO : exit / calcularSaldoFinal()

ABERTO --> FECHADO : fecharCaixa()\n[Calcula saldoFinal]

FECHADO : entry / armazenarRelatorio()
FECHADO : do / permitirConsultas()
FECHADO : exit / arquivarCaixa()

FECHADO --> [*]

@enduml
